### ISSUE TITLE
API breaking changes

### ISSUE THREAD

**Issue by sindikat** [grzegorzbalcerek/ElmByExample#1]
1. I can't find `plainText` function anywhere in core libraries in Elm 0.15.1. `[Text](http://elm-by-example.org/Chapter1HelloWorld.html)` doesn't have it. You use this function in [Chapter 1](http://elm-by-example.org/Chapter1HelloWorld.html). Instead you should use something like `leftAligned` from `[Graphics.Element](package.elm-lang.org/packages/elm-lang/core/2.1.0/Graphics-Element)` library.
2. Same for `asText` in [Chapter 3](http://elm-by-example.org/Chapter3MouseSignals.html), should use `show` or something else instead.
3. In [Chapter 3](http://elm-by-example.org/Chapter3MouseSignals.html) `import List (map)` should be changed to `import List exposing (map)`.
4. [Chapter 5](http://elm-by-example.org/Chapter5Eyes.html) has typos: quater, quoter.
5. In Chapter 5 sometimes you use `*` and sometimes `×` for multiplication

**Comment by grzegorzbalcerek** [comment]
Sorry for late response and thank you for the comments. I am preparing a new version of the tutorial.
