### ISSUE TITLE
Copy error, page 1, second paragraph

### ISSUE THREAD

**Issue by netaisllc** [grzegorzbalcerek/ElmByExample#2]
Guessing this ...

> "The first line — import Text — imports the Graphics.Element module"  

should actually save something like "The first line imports the Graphics.Element module."

![selection_113](https://cloud.githubusercontent.com/assets/1242423/9975017/e0a09350-5e5f-11e5-8534-7db93ee2bfd3.png)

**Comment by grzegorzbalcerek** [comment]
Thank you. Leftover from a previous version. Corrected.
