### ISSUE TITLE
Spelling errors, HW2, HW3

### ISSUE THREAD

**Issue by netaisllc** [grzegorzbalcerek/ElmByExample#3]
s/b 
- separating
- strictly

If you take PRs, I'd be happy to make the changes.

![selection_114](https://cloud.githubusercontent.com/assets/1242423/9975221/e99e171c-5e68-11e5-99d7-8f7432fe396c.png)

**Comment by grzegorzbalcerek** [comment]
Thank you again. No, I do not take PRs. Corrected.
