### ISSUE TITLE
Fancy maps removal

### ISSUE THREAD

**Issue by davidnadeau** [grzegorzbalcerek/ElmByExample#6]
Now that fancy map has been removed from 0.16, how can the mouse signals example be refactored?

```
main =
    showsignals
        <~ Mouse.position
        ~ Mouse.x
        ~ Mouse.y
        ~ Mouse.clicks
        ~ Mouse.isDown
        ~ sampleOn Mouse.clicks Mouse.position
        ~ sampleOn Mouse.isDown Mouse.position
```

**Comment by FranklinChen** [comment]
I see that the standard library defines only up to `map5` http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Signal but `map7` is needed, so I guess just define one's own as with https://github.com/elm-lang/core/blob/master/src/Native/Signal.js#L197

**Comment by davidnadeau** [comment]
Thanks franklin, I was moreso looking for a solution which replaces the fancy maps ability to work on N signals. Turns out that the fancy map functions were moved out of the core to Signal.Extra, so this module con be important, and the <~ and ~ functions work once more.

Also this post on google groups https://groups.google.com/forum/#!topic/elm-discuss/_qrftLBu6g4 shows an example using only core:

```
andMap = Signal.map2 (<|)

main =
    Signal.map showsignals
        Mouse.position
        `andMap` Mouse.x
        `andMap` Mouse.y
        `andMap` Mouse.clicks
        `andMap` Mouse.isDown
        `andMap` sampleOn Mouse.clicks Mouse.position
        `andMap` sampleOn Mouse.isDown Mouse.position
```
