### ISSUE TITLE
Question: plans to migrate o 0.16

### ISSUE THREAD

**Issue by leikind** [grzegorzbalcerek/ElmByExample#7]
Hi,

I started working through you code examples and found out that `<~` and `~` are not in Elm 0.16. I am curious if you have any plans to rewrite these examples to run in 0.16?

**Comment by davidnadeau** [comment]
<~ and ~ were moved out of the core lang and into the Signal.Extra module (http://package.elm-lang.org/packages/Apanatshka/elm-signal-extra/5.7.0/). So this module can be imported, and the code examples will work again.

**Comment by leikind** [comment]
Oh, I didn't know that, thanks for the tip! What is your personal opinion on `<~` vs `Signal.map` and the like? I mean, if you were rewriting your examples for 0.16, would you just add this import, or would you rewrite these operators using more verbose Signal calls?

**Comment by davidnadeau** [comment]
I would import the Signal.Extra module, since the point of these examples is to encourage using elm, and the alternatives are messier. 
Sticking to the core lang, you can define a helper method (taken from here https://groups.google.com/forum/#!topic/elm-discuss/_qrftLBu6g4): 

```
andMap = Signal.map2 (<|)

main =
    Signal.map showsignals
        Mouse.position
        `andMap` Mouse.x
        `andMap` Mouse.y
        `andMap` Mouse.clicks
        `andMap` Mouse.isDown
        `andMap` sampleOn Mouse.clicks Mouse.position
        `andMap` sampleOn Mouse.isDown Mouse.position
```

This is clearly more complicated, and might scare away new users.

**Comment by leikind** [comment]
Ok, I see. I just want to say that these things are really subjective. I personally like this variant, and in my opinion all these `<<`, `>>`, `<|`, `<~` make code less readable. The only awesome operator is `|>`. But it's only my personal opinion.
